"use client";
import { motion } from "framer-motion";
import { ArrowUpRight, Orbit, Sparkles } from "lucide-react";

export function Hero() {
  return <section className="relative overflow-hidden rounded-3xl border border-white/10 bg-gradient-to-b from-white/[0.06] to-white/[0.02] p-8 md:p-16"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 1.2 }} className="max-w-3xl space-y-6"><p className="text-xs uppercase tracking-[0.35em] text-mist">Discernement relationnel</p><h1 className="text-4xl leading-tight md:text-6xl">La cohérence professionnelle devient une infrastructure stratégique.</h1><p className="text-white/70 md:text-lg">ARHI révèle les architectures humaines qui rendent les équipes stables, fluides et performantes sur la durée.</p><button className="rounded-full border border-[#d6c089]/60 bg-[#d2b47b]/10 px-6 py-3 text-sm text-[#f0dfb7]">Découvrir l&apos;expérience</button></motion.div><motion.div animate={{ rotate: 360 }} transition={{ repeat: Infinity, duration: 45, ease: "linear" }} className="absolute -right-20 -top-20 h-72 w-72 rounded-full border border-white/10"/><div className="absolute bottom-8 right-8 hidden gap-4 md:flex"><Orbit className="text-white/40"/><Sparkles className="text-[#d8c08a]"/></div></section>;
}

export function DimensionCards({ items }: { items: string[] }) { return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((item, i) => <motion.article key={item} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ delay: i * 0.06, duration: 0.8 }} className="card p-5"><p className="text-sm text-white/60">Dimension {String(i + 1).padStart(2, "0")}</p><h3 className="mt-2 text-xl">{item}</h3><p className="mt-3 text-sm text-white/65">Lecture contextuelle désynchronisée, pour distinguer posture, rythme et capacité relationnelle.</p></motion.article>)}</div>; }

export function CtaPanel() { return <section className="card mt-16 flex flex-col gap-6 p-8 md:flex-row md:items-center md:justify-between"><div><p className="text-xs uppercase tracking-[0.3em] text-mist">Plateforme ARHI</p><h3 className="mt-2 text-2xl">Élever la qualité des décisions humaines.</h3></div><button className="inline-flex items-center gap-2 rounded-full border border-white/20 px-5 py-3 text-sm">Demander une démonstration <ArrowUpRight size={16}/></button></section>; }
